// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mhbxzpugxeesdsxecgqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1oYnh6cHVneGVlc2RzeGVjZ3F3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0OTU5NzYsImV4cCI6MjA1NjA3MTk3Nn0.vysTpIYVD1dNDNMCFL8jjAECPkNmU5y2c18oh_tHXbk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);